FROM resin/rpi-raspbian:latest
# Dockerfile for the Raspberry Pi that will drive the RC car

# Assembled from official documentation and Ales Ellis' blog post "Getting Started with Docker on Raspberry Pi

ENTRYPOINT []
# reject pre-defined startup and replace it with our own

RUN apt-get update
RUN apt-get -qy install curl ca-certificates 
RUN apt-get -qy install python3 python3-pip 


