FROM resin/raspberrypi3-python
# Dockerfile for the Raspberry Pi that will drive the RC car

# Assembled from official documentation and Ales Ellis' blog post "Getting Started with Docker on Raspberry Pi

ENTRYPOINT []
# reject pre-defined startup and replace it with our own

RUN apt-get update && apt-get -qy install curl wget ca-certificates \
python3-pip python-opencv python-numpy

# 


